### ISSUE TITLE
Babel errors on compiling (minifying) js files

### ISSUE THREAD

**Issue by ElStupid** [failwyn/WebCompiler#15]
### Installed product versions
- Visual Studio: 2022 Community Edition
- This extension: 1.14.1
- Windows 11

### Description
Babel errors on compiling (minifying) js files. I have a VS2019 installation on the same machine, which works just fine (with Mads' extension)

### Steps to recreate
1. any.js
2. set output in compilerconfig.json to any.min.js
    {
        "outputFile": "js/any.min.js",
        "inputFile": "js/any.js"
    }
3. right click and try to compile it

### Current behavior
It doesn't compile, instead give me an error: (copy)

Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: Couldn't find preset "react" relative to directory "C:/website/js"
    at C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Users\el_st\AppData\Local\Temp\WebCompiler1.12.6\node_modules\babel-cli\lib\babel\util.js:50:22)
	MyProject	C:\website\js\any.js	0	

### Expected behavior
Should compile correctly

**Comment by ElStupid** [comment]
PS: I have BundlerMinifier 2022+ installed also

**Comment by failwyn** [comment]
Would you mind using Bunder & Minifier to handle your JavaScript files for the time being? I'm going to look into this issue, but unless it's a relatively simple fix, I'm leaning towards not supporting JavaScript minification since Bundler & Minifier was designed for that specific use case and WebCompiler was more for transformation of styles to css.

**Comment by ElStupid** [comment]
Thanks. I switched to BundlerMinifier for me, works neat too. I only use Webcompiler for less/scss to css now.
As it seems, WebCompiler does minify css by default (which it always did with js too)

I will try to figure out the problem. I can define any js file with a simple 
`var test = true;`
in it, then try to compile and it gives me the error. As if it expects some kind of configuration in that folder. 
Could be my setup or project of course.

**Comment by failwyn** [comment]
It probably has something to do with the updated libraries, the ones in 2019 were pretty old and I updated all of them when I build the 2022 version. I'm gonna try to look at this later in the week when I have some time.

**Comment by ElStupid** [comment]
Alright thanks for looking into it. I have a work around, so no rush ;)
