### ISSUE TITLE
Compilation of less file fails with 7z.dll unhandled exception

### ISSUE THREAD

**Issue by JanVargovsky** [failwyn/WebCompiler#30]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Professional 2022 (64-bit) Version 17.0.6
- This extension: 1.14.4

### Description
Compiling `site.less` fails on access to the path 7z.dll

### Steps to recreate
1. Standard ASP.NET .NET 6 project (Blazor server)
2. have wwwroot/css/site.less
3. run compilation

### Current behavior
Fails on unhandled exception
```log
C:\... repo> C:\USERS\... path to VS\WebCompiler.exe "C:/.../compilerconfig.json" "wwwroot/css/site.less"
	
Unhandled Exception: System.UnauthorizedAccessException: Access to the path '7z.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at WebCompiler.CompilerService.Initialize() in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Compile\CompilerService.cs:line 93
   at WebCompiler.CompilerService.GetCompiler(Config config) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Compile\CompilerService.cs:line 37
   at WebCompiler.ConfigFileProcessor.ProcessConfig(String baseFolder, Config config) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 190
   at WebCompiler.ConfigFileProcessor.Process(String configFile, IEnumerable`1 configs, Boolean force) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Config\ConfigFileProcessor.cs:line 44
   at WebCompiler.Program.Main(String[] args) in W:\Git\Light Speed Solutions\WebCompiler\src\WebCompiler\Program.cs:line 25
Process terminated with code -532462766.
```

### Expected behavior
The file should be compiled/bundled with no exception or at least with meaningful information why is it trying to delete the `7z.dll`.

**Comment by failwyn** [comment]
Can you try the fix outlined [here](https://github.com/madskristensen/WebCompiler/issues/390)?

**Comment by JanVargovsky** [comment]
Well, I've set it to uninstall with next VS close, then ignored it, so it was still installed, and was trying to find other extension and in the meantime, it started working.

**Comment by failwyn** [comment]
It seams like it's a very rare issue based on the number of comments over the last 3 years (on the initial issue in Mads' repo); let me know if it happens to you again, If we can identify a way to reliably reproduce it, I could probably fix it.

**Comment by Velociraptor45** [comment]
I just ran into the same issue, it stopped working from one rebuild to the other. But for me, it was the 7z.exe it couldn't access.
I had to execute only the first 4 steps of your instructions to get it working again:
1. Exit Visual Studio entirely.
2. Open C:\Users%username%\AppData\Local\Temp
3. Find the WebCompiler subfolder for your version and delete it
4. Reopen Visual Studio. This should recreate the WebCompiler subfolder.

Interestingly, when I removed the subfolder, it contained only the 7z.exe. Now after it is fixed, there's a node_modules folder, log.txt & node.exe.

**Comment by b1tzer0** [comment]
I just got a new laptop and the same issues started occurring for me. After following the instructions from Velociraptor45, it seems to have resolved itself.
